#ifndef GENERAL_MANAGEMENT_H
#define GENERAL_MANAGEMENT_H

typedef enum{
	GENERAL_STATE_IDE,
	GENERAL_STATE_BUTTON_PUSHED,
	GENERAL_STATE_WAIT_ACTION,
	GENERAL_STATE_BUTTON_RELEASED,
	GENERAL_STATE_LAUNCH_APP,
	GENERAL_STATE_LAUNCH_DFU
}general_states_t;

bool general_control(void);


#endif


